# Configuration file for MegaLinter
# See all available variables at https://megalinter.io/configuration/ and in linters documentation

APPLY_FIXES: all

# ENABLE: # If you use ENABLE variable, all other languages/formats/tooling formats will be disabled by default
ENABLE:
  - MARKDOWN
  - ANSIBLE

# ENABLE_LINTERS: # If you use ENABLE_LINTERS variable, all other linters will be disabled by default
ENABLE_LINTERS:
  - MARKDOWN_MARKDOWNLINT
  - ANSIBLE_ANSIBLE_LINT

PRINT_ALL_FILES: false

GITHUB_STATUS_REPORTER: true

FILTER_REGEX_EXCLUDE: >
  (\.automation/test|\.automation/generated|\.venv|\.github/workflows|
  docs/javascripts|docs/overrides|docs/json-schemas|flavors|clj-kondo|TEMPLATES)

BASH_FILTER_REGEX_EXCLUDE: "(lib)"

ANSIBLE_ANSIBLE_LINT_CONFIG_FILE: '.ansible-lint.yml'

MARKDOWN_FILTER_REGEX_EXCLUDE: '(license\.md|docs/licenses)'
MARKDOWN_MARKDOWN_LINK_CHECK_DISABLE_ERRORS: true
MARKDOWN_SUMMARY_REPORTER: true

SHOW_ELAPSED_TIME: true

FLAVOR_SUGGESTIONS: false

EMAIL_REPORTER: false

FILEIO_REPORTER: false

JSON_REPORTER: true

PLUGINS:
  - https://raw.githubusercontent.com/oxsecurity/megalinter/main/.automation/test/mega-linter-plugin-test/test.megalinter-descriptor.yml

PRE_COMMANDS:
  - command: ansible-galaxy collection install -r requirements.yml
    cwd: "workspace"
    continue_if_failed: false

POST_COMMANDS:
  - command: echo "All done!"
    cwd: "workspace"
